apiVersion: v1
kind: Namespace
metadata:
  name: demo-app

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/demo-app
    repoURL: https://github.com/tfkhim/devops-dreamland-config.git
    targetRevision: HEAD
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
