apiVersion: v1
kind: Namespace
metadata:
  name: http-echo

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/http-echo
    repoURL: https://github.com/tfkhim/devops-dreamland-config.git
    targetRevision: HEAD
  destination:
    namespace: http-echo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
